### PR TITLE
Updated Linter and Fixed Errors

### PR DESCRIPTION
**Pull request by tomprats**

### CODE REVIEW

**Comment by carsonwright** [comment]
screen shot 2017-09-27 at 11 00 14 am

**Comment by carsonwright** [comment]
Ping me when this is fixed, or if you feel its not relevant, I just figured cause of the branch title.

**Comment by tomprats** [comment]
@carsonwright I think that might be from my WIP commits. Wrestling with IE has proven to be quite painful

**Comment by carsonwright** [comment]
Yeah I bet

**Comment by carsonwright** [comment]
Looks good man!

**Pull request merged**
