### PR TITLE
French updates

### PR DESCRIPTION
**Pull request by Jbur43**
- French updates for show more and show less
- added pitfalls translation
* the last change asked for in this task is included in the dash pr
https://app.asana.com/0/839321118483809/1101218990002677

### CODE REVIEW

**Comment by Jbur43** [comment]
Its not I thought I should add it for standardization

**Comment by tomprats** [comment]
It looks like it often differs from `potential_pitfalls`, so it might be good to update those translations (although maybe it's a contextual thing in the languages).

I don't think we'd want to just have extra translations here. Whenever we add a new one, we can reference Dash to see if it has already been translated there

**Comment by Jbur43** [comment]
I see what youre saying there. I removed it

**Comment by tomprats** [comment]
Can you merge this branch into your other PR?

**Pull request closed without merging**
