### PR TITLE
Enforce import order convention

### PR DESCRIPTION
**Pull request by quangngd**
Can you move this up under the `recoil` import to keep it alphabetical based on path (first external imports, then full paths, and then local paths like "./style")

_Originally posted by @tomprats in https://github.com/traitify/traitify-widgets/pull/322#discussion_r1519983451_
            

Free up the mind of both developers and reviewer

### CODE REVIEW

**Comment by quangngd** [comment]
@tomprats the CI still passes even though it should be failing

**Review by tomprats — APPROVED** [review]
Awesome work! I had implemented this at one point but there was some kind of bug. This will be very helpful now

**Comment by tomprats** [comment]
> @tomprats the CI still passes even though it should be failing.
> 
> But if you run npm run dev the cli still output errors. That alone is useful enough imo but it would be better for the ci to track it

Yeah that's a big issue. I can make a task to fix that if you want to tackle that. I definitely thought that was happening

**Comment by quangngd** [comment]
Fixed. Ready to be merged now.

> > the CI still passes even though it should be failing.
> > But if you run npm run dev the cli still output errors. That alone is useful enough imo but it would be better for the ci to track it
> 
> Yeah that's a big issue. I can make a task to fix that if you want to tackle that. I definitely thought that was happening

The ops team controls all the CI script right? I can't see the CI script anywhere

**Pull request merged**
